#!/bin/sh
set -e
set -x
rm -f ~/.ssh/known_hosts
source /root/keystonerc_admin

ospurge --dont-delete-project --cleanup-project demo
ospurge --dont-delete-project --own-project

glance image-create --name='httpd-1' --visibility public --container-format=bare\
                    --disk-format=qcow2 < httpd-1.qcow2c


glance image-create --name='httpd-2' --visibility public --container-format=bare\
                    --disk-format=qcow2 < httpd-2.qcow2c

cat ~/keystonerc_demo
